### ISSUE TITLE
Pip command not found

### ISSUE THREAD

**Issue by CodeDoctorDE** [DrSnowbird/jdk-mvn-py3#2]
==> Hi, please use pip3 instead of pip due to the base image Ubuntu OS changes:

RUN python3 -m pip install mkdocs

= = = =
I run this command:  `pip install mkdocs` and i get this error:
 /usr/bin/bash: line 96: pip: command not found

**Comment by miparnisari** [comment]
==> Hi, please use pip3 instead of pip due to the base image Ubuntu OS changes:

RUN python3 -m pip install cloudformation-cli cloudformation-cli-java-plugin

= = = = =

Same here.

```
Step 4/12 : FROM openkbs/jre-mvn-py3 as build
 ---> fd33f1fc9efb
Step 5/12 : RUN pip install cloudformation-cli cloudformation-cli-java-plugin
 ---> Running in abaeec083a8c
/bin/sh: 1: pip: not found
```

**Comment by ldelaprade** [comment]
How about adding GIT to that tool set ?

**Comment by DrSnowbird** [comment]
Thanks @ldelaprade , we already now include GIT python module as default PIP modules. Cheers!
